Repository superinsight/superinsight-db, pull requests merged in 2022-11, with the labels that each got.

#20 BUG: Avoid time out when making image to text predictions
  docker/standalone/docker-entrypoint.sh
  src/predict/transformers/README.md
  src/predict/transformers/app.py
  src/proxy/README.md
  src/search/database/queue.py
  src/search/test/README.md
Labels: bug

#21 Change maxlength to new max tokens
  src/predict/transformers/pipeline/text_generation.py
  src/server/README.md
  src/server/ml/pipeline/text_generation.py
Labels: enhancement

#22 Use New Max Token for Text Generation
  src/predict/transformers/pipeline/text_generation.py
  src/server/README.md
  src/server/ml/pipeline/text_generation.py
Labels: enhancement

#24 update readme docker instruction
  README.md
  docs/media/repo-banner.png
Labels: documentation

#26 Merge Fix for log getting too large too quickly
  src/search/ml/pipeline/faiss.py
Labels: bug

#28 27 feat single host with docker compose
  docker/singlehost/.docker-build.sh
  docker/singlehost/README.md
  docker/singlehost/docker-compose.yml
  docker/singlehost/predict/transformers/Dockerfile
  docker/singlehost/predict/transformers/README.md
  docker/singlehost/search/Dockerfile
  docker/singlehost/search/README.md
  docker/singlehost/search/docker-entrypoint.sh
  docker/singlehost/server/Dockerfile
  docker/singlehost/server/README.md
  docker/singlehost/server/docker-entrypoint.sh
  src/search/environment.py
  src/server/environment.py
Labels: enhancement

#31 Docker compose place holder for indexing
  docker/singlehost/docker-compose.yml
Labels: documentation
